import type { MetadataRoute } from "next";
import urlJoin from "url-join";
import { config } from "@/config";

// This function generates the sitemap index file (sitemap.xml)
// It points to the other sitemap files generated by Next.js
export default function sitemap(): MetadataRoute.Sitemap {
  const sitemaps = ["/static/sitemap.xml", "/blog/sitemap.xml", "/tag/sitemap.xml"];

  return sitemaps.map((route) => ({
    url: urlJoin(config.baseUrl, route),
    lastModified: new Date(), // Use current date or fetch specific last modified dates if needed
  }));
}
